---
- hosts: my-vm
  gather_facts: false

  tasks:
   - name: Register a new value
     shell: echo "/etc/resolv.conf"
     register: PLAY1VAR

   - name: Set fact for subsequent job templates
     set_stats:
      data:
        downtime_id: "{{ PLAY1VAR.stdout }}"
