---
- hosts: localhost
  gather_facts: false

  tasks:
   - name: Register a new value
     shell: echo "/etc/resolv.conf"
     register: PLAY1VAR

   - name: Echo the output PLAY1 variable vaule
     shell: cat "{{PLAY1VAR.stdout}}" | tail -1
     register: PLAY1_RESULTS

   - name: Set fact for subsequent job templates
     set_stats:
      data:
        downtime_id: "123"

 


